runtime: python39

instance_class: F1  #0.5cores 0.5GB
service: default
entrypoint: python3 src/main/main.py
service_account: db-mapper@devops-db-resources.iam.gserviceaccount.com
env_variables:
  SERVERLESS_MODE: true
  PYTHONPATH: /srv
  LOG_LEVEL: 'DEBUG'

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
